# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e93362ca2da009fe4973a7a25e500dca1e19efde9016d2987fec073b6bf96722e2bad52f18338a05de9729c5c604643352611a00e814b51bbb4cc5f03ad0e6b

test:
  secret_key_base: 21cee6c04a62310215ab4a0394dbf7cd90ce7c5f9cc3556dd48ca545f8275a5b60602e7ea1a91233ed4e34bf9ea540fad41f8d1083567506c2378684a1602bbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
